In [ ]:
print("Hello python")

Hello python

In [ ]:
numbers = [1, 101,20,2,30]

In [ ]:
len(numbers)

3

In [ ]:
sum(numbers)

60

In [ ]:
max(numbers)

30

In [ ]:
x = 10
x

In [ ]:
min(numbers)

10

In [ ]:
sorted(numbers)

[1, 2, 20, 30, 101]

In [ ]:
salary = -15000
abs(salary)

15000

In [ ]:
round(3.145)

3.15

In [ ]:
round(0.000000000000000145e+15, 3)

0.145

In [ ]:
type(2.15)

float

In [ ]:
values = [4,-2,9,0,11]

In [ ]:
any(i>0 for i in values )#positive

True

In [ ]:
any(i<-3 for i in values ) #negative

False

In [ ]:
all(i>0 for i in values )

False

In [ ]:
dir(values)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
names = ["raj", "Rohan", "Meera"]

In [ ]:
for index, name in enumerate(names, start=12):
  print(index, name)

12 raj
13 Rohan
14 Meera

In [ ]:
numbers

[1, 101, 20, 2, 30]

In [ ]:
value = [10,12,300]

In [ ]:
list(zip(names, value))

[('raj', 10), ('Rohan', 12), ('Meera', 300)]

In [ ]:
dict(zip(names, value))

{'raj': 10, 'Rohan': 12, 'Meera': 300}

In [ ]:
dict(zip(names, numbers))

{'raj': 1, 'Rohan': 101, 'Meera': 20}

In [ ]:
a1 = [-1,-2]

In [ ]:
dict(zip(names, a1))

{'raj': -1, 'Rohan': -2}

In [ ]:
dict(zip(a1, names))

{-1: 'raj', -2: 'Rohan'}

In [ ]:
list(zip(a1, names))

[(-1, 'raj'), (-2, 'Rohan')]

In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

In [ ]:
pd.read_csv?

In [ ]:
# pip install pandas==3.0.0
pd.read_csv("Advertising.csv")

     Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
pd.read_csv("spam.csv", encoding="latin-1")

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [ ]:
df = pd.read_csv("/content/customer_feedback.csv", sep=", ")# first,second

/tmp/ipykernel_1083/847491025.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv("/content/customer_feedback.csv", sep=", ")# first,second

In [ ]:
df.head()

,"""Text",Sentiment,Source,Date/Time,User ID,Location,"Confidence Score"""
0,"""""""I love this product!""""",Positive,Twitter,2023-06-15 09:23:14,@user123,New York,"0.85"""
1,"""""""The service was terrible.""""",Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,"0.65"""
2,"""""""This movie is amazing!""""",Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,"0.92"""
3,"""""""I'm so disappointed with their customer sup...",Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,"0.78"""
4,"""""""Just had the best meal of my life!""""",Positive,TripAdvisor,2023-06-16 08:50:59,foodie22,Paris,"0.88"""

In [ ]:
from sklearn.preprocessing import LabelEncoder #categorical data into numerical
le = LabelEncoder()
a1 = le.fit_transform(df["Sentiment"])

In [ ]:
pd.get_dummies(df["Sentiment"], drop_first=True).astype(int)

    Positive
0          1
1          0
2          1
3          0
4          1
..       ...
91         1
92         0
93         1
94         0
95         1

[96 rows x 1 columns]

In [ ]:
# columns, features, indepe, attributes

# rows, samples, ex, observati

In [ ]:
# categorical=object
# text-----numer==encoding
# nominal: gender = one hot encoder(sklearn), get dummies(pandas) #dimen

# ordinal: education= label encoding

# 1,2,3,4
# 1,3,9

# education:UG=0, PG=1, PHD=2

# gender: male, female, others
# male =   1,     0      0
female =   0,     1      0

In [ ]:
df.head()

,"""Text",Sentiment,Source,Date/Time,User ID,Location,"Confidence Score"""
0,"""""""I love this product!""""",Positive,Twitter,2023-06-15 09:23:14,@user123,New York,"0.85"""
1,"""""""The service was terrible.""""",Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,"0.65"""
2,"""""""This movie is amazing!""""",Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,"0.92"""
3,"""""""I'm so disappointed with their customer sup...",Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,"0.78"""
4,"""""""Just had the best meal of my life!""""",Positive,TripAdvisor,2023-06-16 08:50:59,foodie22,Paris,"0.88"""

In [ ]:
df.shape

(96, 7)

In [ ]:
pd.get_dummies(df, columns=["Sentiment"])

,"""Text",Source,Date/Time,User ID,Location,"Confidence Score""",Sentiment_Negative,Sentiment_Positive
0,"""""""I love this product!""""",Twitter,2023-06-15 09:23:14,@user123,New York,"0.85""",False,True
1,"""""""The service was terrible.""""",Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,"0.65""",True,False
2,"""""""This movie is amazing!""""",IMDb,2023-06-15 14:10:22,moviefan789,London,"0.92""",False,True
3,"""""""I'm so disappointed with their customer sup...",Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,"0.78""",True,False
4,"""""""Just had the best meal of my life!""""",TripAdvisor,2023-06-16 08:50:59,foodie22,Paris,"0.88""",False,True
...,...,...,...,...,...,...,...,...
91,"""""""Just had the most amazing vacation! I can't...",TripAdvisor,2023-07-02 18:01:23,travelenthusiast1,Sydney,"0.93""",False,True
92,"""""""The food at this restaurant was awful. Neve...",Zomato,2023-07-02 20:45:37,foodlover123,Mumbai,"0.55""",True,False
93,"""""""I can't stop listening to this song. It's m...",Spotify,2023-07-03 09:17:52,musiclover789,Berlin,"0.91""",False,True
94,"""""""Their website is so confusing and poorly de...",Website Review,2023-07-03 11:59:18,user789,Toronto,"0.68""",True,False
95,"""""""I had an incredible experience at the theme...",Trip Report,2023-07-03 14:40:05,thrillseeker1,Orlando,"0.89""",False,True

In [ ]:
df["Sentiment"].unique()

array(['Positive', 'Negative'], dtype=object)

In [ ]:
import numpy as np
np.unique(a1)

array([0, 1])

In [ ]:
dict(zip(df["Sentiment"].unique(), np.unique(a1)))

{'Positive': np.int64(0), 'Negative': np.int64(1)}

In [ ]:
df["Sentiment"].values

array(['Positive', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Positive', 'Positive', 'Negative',
       'Positive', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Negative', 'Positive', 'Negative',
       'Positive', 'Positive', 'Negative', 'Negative', 'Negative',
       'Positive', 'Positive', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Positive', 'Positive', 'Negative',
       'Positive', 'Positive', 'Negative', 'Positive', 'Negative',
       'Positive', 'Negative', 'Positive', 'Negative', 'Positive',
       'Positive', 'Positive', 'Negative', 'Positive', 'Negative',
       'Negative', 'Positive', 'Positive', 'Negative', 'Positive',
       'Negative', 'Negative', 'Negative', 'Positive', 'Negative',
       'Positive', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Negative', 'Positive', 'Positive',
       'Positive', 'Negative', 'Positive', 'Positive', 'Negative',
       'Negative', 'Negative', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Negative', 'Positive', 'Negative',
       'Positive', 'Positive', 'Positive', 'Negative', 'Positive',
       'Negative', 'Positive', 'Negative', 'Positive', 'Negative',
       'Positive'], dtype=object)

In [ ]:
# pip install

In [ ]:
# sklearn
#  preprocessing
#   labelencoding

# User Defined functions

In [ ]:
# def function_name(parameters/argument):
#   code block

In [ ]:
def say_hello():
  print("hello welcome")

In [ ]:
a = say_hello()

hello welcome

In [ ]:
def say_hello1():
  return "hello welcome"

In [ ]:
b = say_hello1()

In [ ]:
a

In [ ]:
b

'hello welcome'

In [ ]:
def cal_tool_price(price, quantity):
  total = price*price
  return total

In [ ]:
cal_tool_price(250, 4)

62500

In [ ]:
def add_number(a,b):
  return a+b

In [ ]:
add_number(10,15)

25

In [ ]:
add_number(10,15,20)

TypeError: add_number() takes 2 positional arguments but 3 were given

In [ ]:
add_number(10)

TypeError: add_number() missing 1 required positional argument: 'b'

In [ ]:
def add1(a, b=10):
  return a*b

In [ ]:
add1(10)

100

In [ ]:
add1(10,25)

250

In [ ]:
def add1(a=10, b):
  return a*b

SyntaxError: parameter without a default follows parameter with a default (1096817959.py, line 1)

In [ ]:
def add1(b, c, a=10):
  return a*b

In [ ]:
add1(1,2)

10

In [ ]:
def cal_marks_summary(marks):
  total = sum(marks)
  avg = total/len(marks)
  highest = max(marks)
  lowest = min(marks)
  return total, avg, highest, lowest

In [ ]:
student_marks = [88,98,10.5, 56, 75, 99]

In [ ]:
type(student_marks)

list

In [ ]:
total, avg, highest, lowest = cal_marks_summary(student_marks)

In [ ]:
total, highest, lowest = cal_marks_summary(student_marks)

ValueError: too many values to unpack (expected 3)

In [ ]:
print("Total=----->", total)

Total=-----> 416

In [ ]:
def student_details(name, course):
  print(f"{name} is learning {course}")

In [ ]:
student_details("raj", "python")

raj is learning python

In [ ]:
student_details("python", "raj")

python is learning raj

In [ ]:
student_details(course="python", name="raj")

raj is learning python

In [ ]:
print("{name} is learning {course}".format(name="ram", course="python"))

ram is learning python

In [ ]:
name="ram"
course="python"
print(f"{name} is learning {course}")

ram is learning python

In [ ]:
def add_all(*numbers): #variable length arguments
  total =0
  for i in numbers:
    total+=i
  return total

In [ ]:
add_all(10,20,30)

60

In [ ]:
add_all(10,20,30,40, 50)

150

In [ ]:
x = 10.5
y=10.5

In [ ]:
def show_profiles(**details):#variable length keyword arguments
  for key, value in details.items():
    print(f"{key}:{value}")

In [ ]:
show_profiles(name="neha", age=24, city="bengaluru")

name:neha
age:24
city:bengaluru

In [ ]:
show_profiles(name="neha", age=24, city="bengaluru", enrolled=True)

name:neha
age:24
city:bengaluru
enrolled:True

In [ ]:
def course(course_name, *students,passing_score=50,  **details):
  print(f"course name: {course_name}")
  print(f"scores: {students}")
  print(f"passing_score: {passing_score}")
  print(f"details: {details}")

In [ ]:
course("python", 45,67, 58, 96, passing_score=60, inst="Krishna", duration=5)

course name: python
scores: (45, 67, 58, 96)
passing_score: 50
details: {'inst': 'Krishna', 'duration': 5}

In [ ]:
course("python", 45,67, 58, 96, inst="Krishna", duration=5)

course name: python
scores: (45, 67, 58, 96)
passing_score: 50
details: {'inst': 'Krishna', 'duration': 5}

In [ ]:
def course(*students,passing_score=50, **details, course_name):
  print(f"course name: {course_name}")
  print(f"scores: {students}")
  print(f"passing_score: {passing_score}")
  print(f"details: {details}")

SyntaxError: arguments cannot follow var-keyword argument (254746315.py, line 1)

In [ ]:
global_message = "welcome"

def show_scope():
  local_message ="hi"
  print(local_message)
  print(global_message)

In [ ]:
show_scope()

hi
welcome

In [ ]:
global_message

'welcome'

In [ ]:
local_message

NameError: name 'local_message' is not defined

In [ ]:
counter = 0

def incrment_counter():
  global counter
  counter+=1
  return counter

In [ ]:
incrment_counter()

1

In [ ]:
global counter = 0

def incrment_counter(counter):

  counter+=1
  return counter

SyntaxError: invalid syntax (29331699.py, line 1)

In [ ]:
counter = 0

def incrment_counter(counter):

  counter+=1
  return counter

In [ ]:
# lambda arguments: expression

In [ ]:
sum1 = lambda a,b,c,d: a+b+c+d

In [ ]:
sum1(1,2,3,4)

10

In [ ]:
show_scope.__doc__

In [ ]:
def cal_area(l, w):
  """Return the area of a rectangle"""
  return l*w

In [ ]:
cal_area.__doc__

'Return the area of a rectangle'

In [ ]:
a = lambda x: x**2

In [ ]:
a(5)

25