In [1]:
import pandas as pd

In [21]:
df = pd.read_csv("/content/UsedCarsPrice.csv", na_values=["??", "????"])

In [35]:
df.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170

In [3]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.head(10)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170
5,5,12950,32.0,61000,Diesel,90,0.0,0,2000,3,1170
6,6,16900,27.0,??,Diesel,????,NaN,0,2000,3,1245
7,7,18600,30.0,75889,NaN,90,1.0,0,2000,3,1245
8,8,21500,27.0,19700,Petrol,192,0.0,0,1800,3,1185
9,9,12950,23.0,71138,Diesel,????,NaN,0,1900,3,1105

In [7]:
df.tail(3)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
1444,17,17950,24.0,21716,Petrol,110,1.0,0,1600,3,1105
1445,18,16750,24.0,25563,Petrol,110,0.0,0,1600,3,1065
1446,19,16950,30.0,64359,Petrol,110,1.0,0,1600,3,1105

In [8]:
df.shape

(1447, 11)

In [9]:
df.columns

Index(['Unnamed: 0', 'Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor',
       'Automatic', 'CC', 'Doors', 'Weight'],
      dtype='object')

In [10]:
df["Price"]

0       13500
1       13750
2       13950
3       14950
4       13750
        ...
1442    22000
1443    22750
1444    17950
1445    16750
1446    16950
Name: Price, Length: 1447, dtype: int64

In [11]:
df.Price

0       13500
1       13750
2       13950
3       14950
4       13750
        ...
1442    22000
1443    22750
1444    17950
1445    16750
1446    16950
Name: Price, Length: 1447, dtype: int64

In [12]:
df.Unnamed: 0

In [13]:
df["Unnamed: 0"]

0        0
1        1
2        2
3        3
4        4
        ..
1442    15
1443    16
1444    17
1445    18
1446    19
Name: Unnamed: 0, Length: 1447, dtype: int64

In [14]:
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [18]:
df.shape[0]

1447

In [19]:
(df.isnull().sum()/df.shape[0])*100 #>50% - need drop column, missing value handled

Unnamed: 0     0.000000
Price          0.000000
Age            6.910850
KM             0.000000
FuelType       6.910850
HP             0.000000
MetColor      10.435384
Automatic      0.000000
CC             0.000000
Doors          0.000000
Weight         0.000000
dtype: float64

In [23]:
df.head(12)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170
5,5,12950,32.0,61000.0,Diesel,90.0,0.0,0,2000,3,1170
6,6,16900,27.0,NaN,Diesel,NaN,NaN,0,2000,3,1245
7,7,18600,30.0,75889.0,NaN,90.0,1.0,0,2000,3,1245
8,8,21500,27.0,19700.0,Petrol,192.0,0.0,0,1800,3,1185
9,9,12950,23.0,71138.0,Diesel,NaN,NaN,0,1900,3,1105
10,10,20950,25.0,31461.0,Petrol,192.0,0.0,0,1800,3,1185
11,11,19950,22.0,43610.0,Petrol,192.0,0.0,0,1800,3,1185

In [24]:
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP            float64
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [22]:
(df.isnull().sum()/df.shape[0])*100

Unnamed: 0     0.000000
Price          0.000000
Age            6.910850
KM             1.036628
FuelType       6.910850
HP             0.552868
MetColor      10.435384
Automatic      0.000000
CC             0.000000
Doors          0.000000
Weight         0.000000
dtype: float64

In [25]:
df["FuelType"].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [26]:
df["FuelType"].value_counts()

FuelType
Petrol    1187
Diesel     145
CNG         15
Name: count, dtype: int64

In [29]:
df["FuelType"].value_counts(normalize=True)

FuelType
Petrol    0.881218
Diesel    0.107647
CNG       0.011136
Name: proportion, dtype: float64

In [30]:
df.describe()

,Unnamed: 0,Price,Age,KM,HP,MetColor,Automatic,CC,Weight
count,1447.000000,1447.000000,1347.000000,1432.000000,1439.000000,1296.000000,1447.000000,1447.00000,1447.000000
mean,712.152039,10797.038010,55.435783,68399.185754,101.873523,0.673611,0.055287,1568.25501,1073.066344
std,417.599339,3700.106339,18.698698,37323.374544,15.840499,0.469072,0.228618,187.37913,53.039480
min,0.000000,4350.000000,1.000000,1.000000,69.000000,0.000000,0.000000,1300.00000,1000.000000
25%,350.500000,8450.000000,43.000000,43000.000000,90.000000,0.000000,0.000000,1400.00000,1040.000000
50%,712.000000,9900.000000,60.000000,63389.500000,110.000000,1.000000,0.000000,1600.00000,1070.000000
75%,1073.500000,11950.000000,69.000000,87000.000000,110.000000,1.000000,0.000000,1600.00000,1085.000000
max,1435.000000,32500.000000,80.000000,243000.000000,192.000000,1.000000,1.000000,2000.00000,1615.000000

In [33]:
df[df["Age"]==1]

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
184,184,17795,1.0,1.0,Petrol,98.0,1.0,0,1400,4,1100
185,185,18245,1.0,1.0,Petrol,110.0,1.0,0,1600,5,1075

In [34]:
df[(df["Age"]==1) | (df["KM"]==1)]

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
109,109,32500,NaN,1.0,NaN,116.0,0.0,0,2000,5,1480
117,117,17900,NaN,1.0,Petrol,110.0,1.0,0,1600,3,1105
169,169,17795,9.0,1.0,Petrol,98.0,1.0,0,1400,4,1065
170,170,18245,9.0,1.0,Petrol,110.0,1.0,0,1600,5,1075
184,184,17795,1.0,1.0,Petrol,98.0,1.0,0,1400,4,1100
185,185,18245,1.0,1.0,Petrol,110.0,1.0,0,1600,5,1075
601,601,7500,50.0,1.0,Diesel,90.0,1.0,0,2000,3,1260
1435,1435,6950,76.0,1.0,Petrol,110.0,0.0,0,1600,5,1114

In [42]:
df.describe(include="O")

       FuelType
count      1347
unique        3
top      Petrol
freq       1187

In [37]:
df["Doors"].unique()

array(['three', '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [40]:
df["Doors"] = df["Doors"].replace(['three', '3'], 3).replace(['four', '4'], 4).replace(['five', '5'], 5).replace('2', 2)

/tmp/ipykernel_1485/3383579611.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Doors"] = df["Doors"].replace(['three', '3'], 3).replace(['four', '4'], 4).replace(['five', '5'], 5).replace('2', 2)

In [41]:
df["Doors"].unique()

array([3, 5, 4, 2])

In [43]:
df.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,3,1165
1,1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170

In [47]:
df.loc[[100, 200, 300],["Age", "HP", "Doors"] ]

      Age     HP  Doors
100  20.0  110.0      3
200  44.0  110.0      5
300  37.0  110.0      5

In [44]:
df.loc[:4,["Age", "HP", "Doors"] ]

    Age    HP  Doors
0  23.0  90.0      3
1  23.0  90.0      3
2  24.0  90.0      3
3  26.0  90.0      3
4  30.0  90.0      3

In [45]:
df.iloc[:4,[1,3,8] ]

   Price       KM    CC
0  13500  46986.0  2000
1  13750  72937.0  2000
2  13950  41711.0  2000
3  14950  48000.0  2000

In [50]:
df.iloc[2:4, 2:4]

    Age       KM
2  24.0  41711.0
3  26.0  48000.0

In [54]:
df.describe(include="O")

       FuelType
count      1347
unique        3
top      Petrol
freq       1187

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1447 entries, 0 to 1446
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1447 non-null   int64
 1   Price       1447 non-null   int64
 2   Age         1347 non-null   float64
 3   KM          1432 non-null   float64
 4   FuelType    1347 non-null   object
 5   HP          1439 non-null   float64
 6   MetColor    1296 non-null   float64
 7   Automatic   1447 non-null   int64
 8   CC          1447 non-null   int64
 9   Doors       1447 non-null   int64
 10  Weight      1447 non-null   int64
dtypes: float64(4), int64(6), object(1)
memory usage: 124.5+ KB

In [56]:
df['new_column'] = df["Price"]*12

In [57]:
df.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight,new_column
0,0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,3,1165,162000
1,1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165,165000
2,2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165,167400
3,3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165,179400
4,4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170,165000

In [59]:
df["Subtraction of cc and weight"] = df["CC"] - df["Weight"]

In [60]:
df.to_csv("updated.csv")

In [63]:
df.drop("CC", axis=1, inplace=True)

In [64]:
df.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,Doors,Weight,new_column,Subtraction of cc and weight
0,0,13500,23.0,46986.0,Diesel,90.0,1.0,0,3,1165,162000,835
1,1,13750,23.0,72937.0,Diesel,90.0,1.0,0,3,1165,165000,835
2,2,13950,24.0,41711.0,Diesel,90.0,NaN,0,3,1165,167400,835
3,3,14950,26.0,48000.0,Diesel,90.0,0.0,0,3,1165,179400,835
4,4,13750,30.0,38500.0,Diesel,90.0,0.0,0,3,1170,165000,830

In [67]:
df.isnull().sum()

Unnamed: 0                      0
Price                           0
Age                             0
KM                              0
FuelType                        0
HP                              0
MetColor                        0
Automatic                       0
Doors                           0
Weight                          0
new_column                      0
Subtraction of cc and weight    0
dtype: int64

In [66]:
df.dropna(inplace=True)

In [68]:
df.head(10)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,Doors,Weight,new_column,Subtraction of cc and weight
0,0,13500,23.0,46986.0,Diesel,90.0,1.0,0,3,1165,162000,835
1,1,13750,23.0,72937.0,Diesel,90.0,1.0,0,3,1165,165000,835
3,3,14950,26.0,48000.0,Diesel,90.0,0.0,0,3,1165,179400,835
4,4,13750,30.0,38500.0,Diesel,90.0,0.0,0,3,1170,165000,830
5,5,12950,32.0,61000.0,Diesel,90.0,0.0,0,3,1170,155400,830
8,8,21500,27.0,19700.0,Petrol,192.0,0.0,0,3,1185,258000,615
10,10,20950,25.0,31461.0,Petrol,192.0,0.0,0,3,1185,251400,615
11,11,19950,22.0,43610.0,Petrol,192.0,0.0,0,3,1185,239400,615
12,12,19600,25.0,32189.0,Petrol,192.0,0.0,0,3,1185,235200,615
13,13,21500,31.0,23000.0,Petrol,192.0,1.0,0,3,1185,258000,615

In [71]:
df.sort_values("Age", ascending=False)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,Doors,Weight,new_column,Subtraction of cc and weight
1414,1414,7500,80.0,42186.0,Petrol,110.0,1.0,0,3,1050,90000,550
1369,1369,8250,80.0,57787.0,Petrol,86.0,0.0,0,3,1015,99000,285
1051,1051,6150,80.0,194765.0,Diesel,72.0,0.0,0,3,1120,73800,880
1430,1430,8450,80.0,23000.0,Petrol,86.0,0.0,0,3,1015,101400,285
1423,1423,7950,80.0,35821.0,Petrol,86.0,0.0,1,3,1015,95400,285
...,...,...,...,...,...,...,...,...,...,...,...,...
111,111,31275,4.0,1500.0,Diesel,116.0,1.0,0,5,1480,375300,520
110,110,31000,4.0,4000.0,Diesel,116.0,1.0,0,5,1480,372000,520
182,182,21125,2.0,225.0,Petrol,97.0,1.0,0,5,1110,253500,290
184,184,17795,1.0,1.0,Petrol,98.0,1.0,0,4,1100,213540,300
185,185,18245,1.0,1.0,Petrol,110.0,1.0,0,5,1075,218940,525

In [80]:
df1 = df.sort_values(["Age", "Price"], ascending=False)

In [81]:
df1.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,Doors,Weight,new_column,Subtraction of cc and weight
1307,1307,9950,80.0,69904.0,Petrol,110.0,0.0,0,5,1070,119400,530
1182,1182,9900,80.0,92255.0,Petrol,107.0,0.0,1,5,1105,118800,495
1081,1081,9500,80.0,137178.0,Diesel,90.0,1.0,0,5,1135,114000,865
1323,1323,9450,80.0,66843.0,Petrol,110.0,1.0,0,5,1075,113400,525
1215,1215,8950,80.0,86000.0,Petrol,110.0,0.0,0,3,1050,107400,550

In [84]:
df1.reset_index(drop=True, inplace=True)

In [85]:
df1

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,Doors,Weight,new_column,Subtraction of cc and weight
0,1307,9950,80.0,69904.0,Petrol,110.0,0.0,0,5,1070,119400,530
1,1182,9900,80.0,92255.0,Petrol,107.0,0.0,1,5,1105,118800,495
2,1081,9500,80.0,137178.0,Diesel,90.0,1.0,0,5,1135,114000,865
3,1323,9450,80.0,66843.0,Petrol,110.0,1.0,0,5,1075,113400,525
4,1215,8950,80.0,86000.0,Petrol,110.0,0.0,0,3,1050,107400,550
...,...,...,...,...,...,...,...,...,...,...,...,...
1100,111,31275,4.0,1500.0,Diesel,116.0,1.0,0,5,1480,375300,520
1101,110,31000,4.0,4000.0,Diesel,116.0,1.0,0,5,1480,372000,520
1102,182,21125,2.0,225.0,Petrol,97.0,1.0,0,5,1110,253500,290
1103,185,18245,1.0,1.0,Petrol,110.0,1.0,0,5,1075,218940,525
1104,184,17795,1.0,1.0,Petrol,98.0,1.0,0,4,1100,213540,300

In [86]:
df.shape

(1105, 12)

In [90]:
df["Unnamed: 0"].nunique()

1096

In [92]:
1105-1096

9

In [91]:
df.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,Doors,Weight,new_column,Subtraction of cc and weight
0,0,13500,23.0,46986.0,Diesel,90.0,1.0,0,3,1165,162000,835
1,1,13750,23.0,72937.0,Diesel,90.0,1.0,0,3,1165,165000,835
3,3,14950,26.0,48000.0,Diesel,90.0,0.0,0,3,1165,179400,835
4,4,13750,30.0,38500.0,Diesel,90.0,0.0,0,3,1170,165000,830
5,5,12950,32.0,61000.0,Diesel,90.0,0.0,0,3,1170,155400,830

In [94]:
df2  = df.reset_index()

In [96]:
df2.head(3)

,index,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,Doors,Weight,new_column,Subtraction of cc and weight
0,0,0,13500,23.0,46986.0,Diesel,90.0,1.0,0,3,1165,162000,835
1,1,1,13750,23.0,72937.0,Diesel,90.0,1.0,0,3,1165,165000,835
2,3,3,14950,26.0,48000.0,Diesel,90.0,0.0,0,3,1165,179400,835

In [ ]:
df

In [100]:
df2[df2["index"]!=df2["Unnamed: 0"]]

,index,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,Doors,Weight,new_column,Subtraction of cc and weight
1096,1437,10,20950,25.0,31461.0,Petrol,192.0,0.0,0,3,1185,251400,615
1097,1438,11,19950,22.0,43610.0,Petrol,192.0,0.0,0,3,1185,239400,615
1098,1439,12,19600,25.0,32189.0,Petrol,192.0,0.0,0,3,1185,235200,615
1099,1440,13,21500,31.0,23000.0,Petrol,192.0,1.0,0,3,1185,258000,615
1100,1441,14,22500,32.0,34131.0,Petrol,192.0,1.0,0,3,1185,270000,615
1101,1443,16,22750,30.0,34000.0,Petrol,192.0,1.0,0,3,1185,273000,615
1102,1444,17,17950,24.0,21716.0,Petrol,110.0,1.0,0,3,1105,215400,495
1103,1445,18,16750,24.0,25563.0,Petrol,110.0,0.0,0,3,1065,201000,535
1104,1446,19,16950,30.0,64359.0,Petrol,110.0,1.0,0,3,1105,203400,495

In [101]:
d1 = pd.read_csv("/content/NSE-TATAGLOBAL.csv")

In [102]:
d1.isnull().sum()

Date                    0
Open                    0
High                    0
Low                     0
Last                    0
Close                   0
Total Trade Quantity    0
Turnover (Lacs)         0
dtype: int64

In [108]:
d1["Date"] = pd.to_datetime(d1["Date"])

In [109]:
d1.head()

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0,2018-09-28,234.05,235.95,230.20,233.50,233.75,3069914,7162.35
1,2018-09-27,234.55,236.80,231.10,233.80,233.25,5082859,11859.95
2,2018-09-26,240.00,240.00,232.50,235.00,234.25,2240909,5248.60
3,2018-09-25,233.30,236.75,232.00,236.25,236.10,2349368,5503.90
4,2018-09-24,233.55,239.20,230.75,234.00,233.30,3423509,7999.55

In [110]:
d1.dtypes

Date                    datetime64[ns]
Open                           float64
High                           float64
Low                            float64
Last                           float64
Close                          float64
Total Trade Quantity             int64
Turnover (Lacs)                float64
dtype: object

In [114]:
d1.sort_values("Date", ascending=False, inplace=True)

In [115]:
d1.head()

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0,2018-09-28,234.05,235.95,230.20,233.50,233.75,3069914,7162.35
1,2018-09-27,234.55,236.80,231.10,233.80,233.25,5082859,11859.95
2,2018-09-26,240.00,240.00,232.50,235.00,234.25,2240909,5248.60
3,2018-09-25,233.30,236.75,232.00,236.25,236.10,2349368,5503.90
4,2018-09-24,233.55,239.20,230.75,234.00,233.30,3423509,7999.55

In [116]:
d1.tail()

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
2030,2010-07-27,117.6,119.50,112.00,118.80,118.65,586100,694.98
2031,2010-07-26,120.1,121.00,117.10,117.10,117.60,658440,780.01
2032,2010-07-23,121.8,121.95,120.25,120.35,120.65,281312,340.31
2033,2010-07-22,120.3,122.00,120.25,120.75,120.90,293312,355.17
2034,2010-07-21,122.1,123.00,121.05,121.10,121.55,658666,803.56

In [119]:
date1 = pd.date_range(start="2010-07-21", end="2018-09-28", freq="B")

In [121]:
date2 = pd.DataFrame(date1, columns=["Date"])

In [122]:
d1.shape

(2035, 8)

In [123]:
date2.shape

(2138, 1)

In [127]:
2138-2035

103

In [125]:
updated = pd.merge(d1, date2,  on="Date", how="right")

In [126]:
updated.isnull().sum()

Date                      0
Open                    112
High                    112
Low                     112
Last                    112
Close                   112
Total Trade Quantity    112
Turnover (Lacs)         112
dtype: int64

In [128]:
df1 = pd.read_csv("/content/weather3.csv")
df2 = pd.read_csv("/content/weather_by_cities.csv")

In [129]:
df1

        date      city  temperature  humidity
0   5/1/2017  new york         65.0      56.0
1   5/2/2017  new york         61.0      54.0
2   5/3/2017       NaN         70.0      60.0
3  12/1/2017  new york         30.0      50.0
4  12/2/2017  new york         28.0       NaN
5  12/3/2017  new york         25.0      51.0
6   5/3/2017  new york         70.0      60.0
7   5/3/2017  new york          NaN      60.0
8   5/3/2017  new york         70.0      60.0
9   5/3/2017       NaN         70.0      60.0

In [130]:
df2

           day      city   temperature  windspeed   event
0   01-01-2017  new york  3.200000e+01          6    Rain
1   01-02-2017  new york  3.600000e+01          7   Sunny
2   01-03-2017  new york -1.000000e+10         12    Snow
3   01-04-2017  new york  3.300000e+01          7   Sunny
4   01-01-2017       NaN  9.000000e+01          5   Sunny
5   01-02-2017    mumbai  8.500000e+01         12     Fog
6   01-03-2017    mumbai  8.700000e+01         15     Fog
7   01-04-2017    mumbai           NaN          5    Rain
8   01-01-2017     paris  4.500000e+01         20   Sunny
9   01-02-2017     paris  5.000000e+01         13  Cloudy
10  01-03-2017     paris  5.400000e+01          8  Cloudy
11  01-04-2017     paris  4.200000e+01         10  Cloudy

In [135]:
pd.merge(df1, df2, on="city", how="right", suffixes=["_left","_right"])

,date,city,temperature_left,humidity,day,temperature_right,windspeed,event
0,5/1/2017,new york,65.0,56.0,01-01-2017,3.200000e+01,6,Rain
1,5/2/2017,new york,61.0,54.0,01-01-2017,3.200000e+01,6,Rain
2,12/1/2017,new york,30.0,50.0,01-01-2017,3.200000e+01,6,Rain
3,12/2/2017,new york,28.0,NaN,01-01-2017,3.200000e+01,6,Rain
4,12/3/2017,new york,25.0,51.0,01-01-2017,3.200000e+01,6,Rain
5,5/3/2017,new york,70.0,60.0,01-01-2017,3.200000e+01,6,Rain
6,5/3/2017,new york,NaN,60.0,01-01-2017,3.200000e+01,6,Rain
7,5/3/2017,new york,70.0,60.0,01-01-2017,3.200000e+01,6,Rain
8,5/1/2017,new york,65.0,56.0,01-02-2017,3.600000e+01,7,Sunny
9,5/2/2017,new york,61.0,54.0,01-02-2017,3.600000e+01,7,Sunny
10,12/1/2017,new york,30.0,50.0,01-02-2017,3.600000e+01,7,Sunny
11,12/2/2017,new york,28.0,NaN,01-02-2017,3.600000e+01,7,Sunny
12,12/3/2017,new york,25.0,51.0,01-02-2017,3.600000e+01,7,Sunny
13,5/3/2017,new york,70.0,60.0,01-02-2017,3.600000e+01,7,Sunny
14,5/3/2017,new york,NaN,60.0,01-02-2017,3.600000e+01,7,Sunny
15,5/3/2017,new york,70.0,60.0,01-02-2017,3.600000e+01,7,Sunny
16,5/1/2017,new york,65.0,56.0,01-03-2017,-1.000000e+10,12,Snow
17,5/2/2017,new york,61.0,54.0,01-03-2017,-1.000000e+10,12,Snow
18,12/1/2017,new york,30.0,50.0,01-03-2017,-1.000000e+10,12,Snow
19,12/2/2017,new york,28.0,NaN,01-03-2017,-1.000000e+10,12,Snow
20,12/3/2017,new york,25.0,51.0,01-03-2017,-1.000000e+10,12,Snow
21,5/3/2017,new york,70.0,60.0,01-03-2017,-1.000000e+10,12,Snow
22,5/3/2017,new york,NaN,60.0,01-03-2017,-1.000000e+10,12,Snow
23,5/3/2017,new york,70.0,60.0,01-03-2017,-1.000000e+10,12,Snow
24,5/1/2017,new york,65.0,56.0,01-04-2017,3.300000e+01,7,Sunny
25,5/2/2017,new york,61.0,54.0,01-04-2017,3.300000e+01,7,Sunny
26,12/1/2017,new york,30.0,50.0,01-04-2017,3.300000e+01,7,Sunny
27,12/2/2017,new york,28.0,NaN,01-04-2017,3.300000e+01,7,Sunny
28,12/3/2017,new york,25.0,51.0,01-04-2017,3.300000e+01,7,Sunny
29,5/3/2017,new york,70.0,60.0,01-04-2017,3.300000e+01,7,Sunny
30,5/3/2017,new york,NaN,60.0,01-04-2017,3.300000e+01,7,Sunny
31,5/3/2017,new york,70.0,60.0,01-04-2017,3.300000e+01,7,Sunny
32,5/3/2017,NaN,70.0,60.0,01-01-2017,9.000000e+01,5,Sunny
33,5/3/2017,NaN,70.0,60.0,01-01-2017,9.000000e+01,5,Sunny
34,NaN,mumbai,NaN,NaN,01-02-2017,8.500000e+01,12,Fog
35,NaN,mumbai,NaN,NaN,01-03-2017,8.700000e+01,15,Fog
36,NaN,mumbai,NaN,NaN,01-04-2017,NaN,5,Rain
37,NaN,paris,NaN,NaN,01-01-2017,4.500000e+01,20,Sunny
38,NaN,paris,NaN,NaN,01-02-2017,5.000000e+01,13,Cloudy
39,NaN,paris,NaN,NaN,01-03-2017,5.400000e+01,8,Cloudy
40,NaN,paris,NaN,NaN,01-04-2017,4.200000e+01,10,Cloudy

In [136]:
a1 = pd.read_csv("/content/north_america_2000_2010.csv")
a2 = pd.read_csv("/content/south_america_2000_2010.csv")

In [137]:
a1

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,Canada,1779.0,1771.0,1754.0,1740.0,1760.0,1747,1745.0,1741.0,1735,1701.0,1703.0
1,Mexico,2311.2,2285.2,2271.2,2276.5,2270.6,2281,2280.6,2261.4,2258,2250.2,2242.4
2,USA,1836.0,1814.0,1810.0,1800.0,1802.0,1799,1800.0,1798.0,1792,1767.0,1778.0

In [139]:
a1.columns==a2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [138]:
a2

  Country  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009    2010
0   Chile  2263  2242  2250  2235  2232  2157  2165  2128  2095  2074  2069.6

In [141]:
pd.concat([a1, a2], axis=0)

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,Canada,1779.0,1771.0,1754.0,1740.0,1760.0,1747,1745.0,1741.0,1735,1701.0,1703.0
1,Mexico,2311.2,2285.2,2271.2,2276.5,2270.6,2281,2280.6,2261.4,2258,2250.2,2242.4
2,USA,1836.0,1814.0,1810.0,1800.0,1802.0,1799,1800.0,1798.0,1792,1767.0,1778.0
0,Chile,2263.0,2242.0,2250.0,2235.0,2232.0,2157,2165.0,2128.0,2095,2074.0,2069.6